/**
 * This file is automatically generated. Do not edit it directly.
 */
import { createClient } from '@supabase/supabase-js';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const SUPABASE_URL = "https://bkgisawsfugswojpjuwk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJrZ2lzYXdzZnVnc3dvanBqdXdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIxNTM5NjMsImV4cCI6MjA4NzcyOTk2M30.YfGNqLbnFYCkdoOUTzTuLhXAKaKzwU3c9mBAUD_RsDE";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);